cp ../yadfm3/.gitignore .
cp ../yadfm3/data/art/ironhand.png data/art/
cp ../yadfm3/data/art/mayday-sans-highlight.png data/art/
cp ../yadfm3/data/art/mayday.png data/art/
cp ../yadfm3/data/art/maydayMIN-sans-highlight.png data/art/
cp ../yadfm3/data/art/maydayMIN.png data/art/
cp ../yadfm3/data/init/colors.txt data/init/
cp ../yadfm3/data/init/d_init.txt data/init/
cp ../yadfm3/data/init/d_init.txt.rej data/init/
cp ../yadfm3/data/init/embark_profiles.txt data/init/
cp ../yadfm3/data/init/init.txt data/init/
cp ../yadfm3/data/init/init.txt.rej data/init/
cp ../yadfm3/data/init/interface.txt data/init/
cp ../yadfm3/data/init/world_gen.txt data/init/
cp ../yadfm3/data/sound/ironhand.ogg data/sound/
cp ../yadfm3/data/speech/dwarf.txt data/speech/
cp ../yadfm3/data/speech/elf.txt data/speech/
cp ../yadfm3/data/speech/female.txt data/speech/
cp ../yadfm3/data/speech/general.txt data/speech/
cp ../yadfm3/data/speech/guard_warning.txt data/speech/
cp ../yadfm3/data/speech/human_male.txt data/speech/
cp ../yadfm3/data/speech/male.txt data/speech/
cp ../yadfm3/data/speech/scouting_profession.txt data/speech/
cp ../yadfm3/data/speech/scouting_profession_year.txt data/speech/
cp ../yadfm3/data/speech/slayer.txt data/speech/
cp ../yadfm3/data/speech/threat.txt data/speech/
cp ../yadfm3/df.ico .
mkdir -p modding
cp ../yadfm3/raw/graphics/critters.png raw/graphics/
cp ../yadfm3/raw/graphics/dwarves.png raw/graphics/
cp ../yadfm3/raw/graphics/graphics_critters.txt raw/graphics/
cp ../yadfm3/raw/graphics/graphics_dwarves.txt raw/graphics/
cp ../yadfm3/raw/graphics/graphics_humies.txt raw/graphics/
cp ../yadfm3/raw/graphics/graphics_kobolds_haggle.txt raw/graphics/
cp ../yadfm3/raw/graphics/graphics_sphr_elves.txt raw/graphics/
cp ../yadfm3/raw/graphics/graphics_sphr_goblins.txt raw/graphics/
cp ../yadfm3/raw/graphics/graphics_sphr_humans.txt raw/graphics/
cp ../yadfm3/raw/graphics/graphics_yadfm.txt raw/graphics/
cp ../yadfm3/raw/graphics/graphics_yadfm_dwarves.txt raw/graphics/
cp ../yadfm3/raw/graphics/humanoids.png raw/graphics/
cp ../yadfm3/raw/graphics/kobolds/kobolds_haggle.bmp raw/graphics/
mkdir -p raw/graphics/mayday
cp ../yadfm3/raw/graphics/mayday/animals.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/beasts.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/dorfs.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/elves.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/gibbon.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/goblins.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/humans.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/kobolds.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/mans.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/newbeasts.png raw/graphics/mayday/
cp ../yadfm3/raw/graphics/mayday/water.png raw/graphics/mayday/
mkdir -p raw/graphics/phoebus
cp ../yadfm3/raw/graphics/phoebus/medics.bmp raw/graphics/phoebus/
mkdir -p raw/graphics/sphr
cp ../yadfm3/raw/graphics/sphr/dwarves.bmp raw/graphics/sphr/
cp ../yadfm3/raw/graphics/sphr/elves.bmp raw/graphics/sphr/
cp ../yadfm3/raw/graphics/sphr/goblins.bmp raw/graphics/sphr/
cp ../yadfm3/raw/graphics/sphr/humans.bmp raw/graphics/sphr/
cp ../yadfm3/raw/graphics/sphr/large_mountain.bmp raw/graphics/sphr/
cp ../yadfm3/raw/graphics/sphr/large_riverlake.bmp raw/graphics/sphr/
cp ../yadfm3/raw/graphics/sphr/monsters.bmp raw/graphics/sphr/
cp ../yadfm3/raw/graphics/sphr/subterranean.bmp raw/graphics/sphr/
cp ../yadfm3/raw/graphics/sphr/wildlife.bmp raw/graphics/sphr/
cp ../yadfm3/raw/objects/b_detail_plan_default.txt raw/objects/
cp ../yadfm3/raw/objects/body_cf.txt raw/objects/
cp ../yadfm3/raw/objects/body_rcp_cf.txt raw/objects/
cp ../yadfm3/raw/objects/building_custom_enhanced.txt raw/objects/
cp ../yadfm3/raw/objects/building_kobold.txt raw/objects/
cp ../yadfm3/raw/objects/c_variation_tanmod.txt raw/objects/
cp ../yadfm3/raw/objects/creature_birds.txt raw/objects/
cp ../yadfm3/raw/objects/creature_domestic.txt raw/objects/
cp ../yadfm3/raw/objects/creature_domestic_enhanced.txt raw/objects/
cp ../yadfm3/raw/objects/creature_elemental_enhanced.txt raw/objects/
cp ../yadfm3/raw/objects/creature_equipment.txt raw/objects/
cp ../yadfm3/raw/objects/creature_insects_enhanced.txt raw/objects/
cp ../yadfm3/raw/objects/creature_large_mountain.txt raw/objects/
cp ../yadfm3/raw/objects/creature_large_ocean.txt raw/objects/
cp ../yadfm3/raw/objects/creature_large_riverlake.txt raw/objects/
cp ../yadfm3/raw/objects/creature_large_temperate.txt raw/objects/
cp ../yadfm3/raw/objects/creature_large_temperate_enhanced.txt raw/objects/
cp ../yadfm3/raw/objects/creature_large_tropical.txt raw/objects/
cp ../yadfm3/raw/objects/creature_large_tundra.txt raw/objects/
cp ../yadfm3/raw/objects/creature_large_tundra_cf.txt raw/objects/
cp ../yadfm3/raw/objects/creature_next_underground.txt raw/objects/
cp ../yadfm3/raw/objects/creature_other.txt raw/objects/
cp ../yadfm3/raw/objects/creature_reptiles.txt raw/objects/
cp ../yadfm3/raw/objects/creature_savage_tropical.txt raw/objects/
cp ../yadfm3/raw/objects/creature_small_mammals_enhanced.txt raw/objects/
cp ../yadfm3/raw/objects/creature_small_ocean.txt raw/objects/
cp ../yadfm3/raw/objects/creature_small_riverlake.txt raw/objects/
cp ../yadfm3/raw/objects/creature_standard_enhanced.txt raw/objects/
cp ../yadfm3/raw/objects/creature_subterranean.txt raw/objects/
cp ../yadfm3/raw/objects/descriptor_pattern_cf.txt raw/objects/
cp ../yadfm3/raw/objects/entity_giant_frost_cf.txt raw/objects/
cp ../yadfm3/raw/objects/entity_middle_earth.txt raw/objects/
cp ../yadfm3/raw/objects/inorganic_metal.txt raw/objects/
cp ../yadfm3/raw/objects/inorganic_tanmod.txt raw/objects/
cp ../yadfm3/raw/objects/item_gloves.txt raw/objects/
cp ../yadfm3/raw/objects/item_shield.txt raw/objects/
cp ../yadfm3/raw/objects/item_shoes.txt raw/objects/
cp ../yadfm3/raw/objects/item_wanderer.txt raw/objects/
cp ../yadfm3/raw/objects/language_DWARF.txt raw/objects/
cp ../yadfm3/raw/objects/language_ELF.txt raw/objects/
cp ../yadfm3/raw/objects/language_GOBLIN.txt raw/objects/
cp ../yadfm3/raw/objects/language_HUMAN.txt raw/objects/
cp ../yadfm3/raw/objects/language_KOBOLD.txt raw/objects/
cp ../yadfm3/raw/objects/language_SYM.txt raw/objects/
cp ../yadfm3/raw/objects/language_words.txt raw/objects/
cp ../yadfm3/raw/objects/material_template_creature_cf.txt raw/objects/
cp ../yadfm3/raw/objects/material_template_default.txt raw/objects/
cp ../yadfm3/raw/objects/material_template_kobold.txt raw/objects/
cp ../yadfm3/raw/objects/material_template_plant_cf.txt raw/objects/
cp ../yadfm3/raw/objects/plant_cf.txt raw/objects/
cp ../yadfm3/raw/objects/plant_standard.txt raw/objects/
