rm TO-DO.txt
rm apply-charpatch.sh
rm biomes.txt
rm charfix.pl
rm data/art/ironhand.png
rm data/art/mayday-sans-highlight.png
rm data/art/mayday.png
rm data/art/maydayMIN-sans-highlight.png
rm data/art/maydayMIN.png
rm data/init/d_init.txt.rej
rm data/init/embark_profiles.txt
rm data/init/init.txt.rej
rm data/sound/ironhand.ogg
rm data/speech/female.txt
rm data/speech/human_male.txt
rm data/speech/male.txt
rm df.ico
rm items-to-races.txt
rm mayday-patch.sh
rm -rf modding/
rm racial-names.txt
rm raw/graphics/critters.png
rm raw/graphics/dwarves.png
rm raw/graphics/graphics_critters.txt
rm raw/graphics/graphics_dwarves.txt
rm raw/graphics/graphics_humies.txt
rm raw/graphics/graphics_kobolds_haggle.txt
rm raw/graphics/graphics_sphr_elves.txt
rm raw/graphics/graphics_sphr_goblins.txt
rm raw/graphics/graphics_sphr_humans.txt
rm raw/graphics/graphics_yadfm.txt
rm raw/graphics/graphics_yadfm_dwarves.txt
rm raw/graphics/humanoids.png
rm raw/graphics/kobolds_haggle.bmp
rm -rf raw/graphics/mayday/
rm -rf raw/graphics/phoebus/
rm -rf raw/graphics/sphr/
rm raw/objects/body_cf.txt
rm raw/objects/body_rcp_cf.txt
rm raw/objects/building_custom_enhanced.txt
rm raw/objects/building_kobold.txt
rm raw/objects/c_variation_tanmod.txt
rm raw/objects/creature_domestic_enhanced.txt
rm raw/objects/creature_elemental_enhanced.txt
rm raw/objects/creature_insects_enhanced.txt
rm raw/objects/creature_large_temperate_enhanced.txt
rm raw/objects/creature_large_tundra_cf.txt
rm raw/objects/creature_small_mammals_enhanced.txt
rm raw/objects/creature_standard_enhanced.txt
rm raw/objects/descriptor_pattern_cf.txt
rm raw/objects/entity_giant_frost_cf.txt
rm raw/objects/entity_middle_earth.txt
rm raw/objects/inorganic_metal_enhanced.txt
rm raw/objects/inorganic_stone_mineral_enhanced.txt
rm raw/objects/inorganic_tanmod.txt
rm raw/objects/item_ammo_enhanced.txt
rm raw/objects/item_armor_enhanced.txt
rm raw/objects/item_food_enhanced.txt
rm raw/objects/item_gloves_enhanced.txt
rm raw/objects/item_helm_enhanced.txt
rm raw/objects/item_instrument_enhanced.txt
rm raw/objects/item_pants_enhanced.txt
rm raw/objects/item_shield_enhanced.txt
rm raw/objects/item_shoes_enhanced.txt
rm raw/objects/item_toy_enhanced.txt
rm raw/objects/item_trapcomp_enhanced.txt
rm raw/objects/item_wanderer.txt
rm raw/objects/item_weapon_enhanced.txt
rm raw/objects/language_KOBOLD.txt
rm raw/objects/material_template_creature_cf.txt
rm raw/objects/material_template_kobold.txt
rm raw/objects/material_template_plant_cf.txt
rm raw/objects/plant_cf.txt
rm raw/objects/reaction_advleather.txt
rm raw/objects/reaction_kobold.txt
rm raw/objects/reaction_other_enhanced.txt
rm raw/objects/reaction_primitive_cf.txt
rm raw/objects/reaction_smelter_enhanced.txt
rm raw/objects/reaction_tanmod.txt
rm raw/objects/reaction_wanderer.txt
rm raw/objects/reaction_wanderer_tanmod.txt
